### PR TITLE
Update spec

### PR DESCRIPTION
**Pull request by macumber**

### CODE REVIEW

**Comment by macumber** [comment]
@nllong can you take a quick look at change to lib/seed/search.rb?

It seems that there is no longer a results section, it just has properties directly

**Comment by nllong** [comment]
i'm looking into the search and fixing the unit tests.

**Comment by nllong** [comment]
@macumber this should be good to go now. Everything is passing based off the new bricr docker containers published here (https://hub.docker.com/r/seedplatform/seed/tags/).

**Review by nllong — APPROVED** [review]
Looks good. Merge away.

**Pull request merged**
